#!/usr/bin/env bash
# installs and configures nginx web server on a remote server
sudo apt-get -y install nginx;
sudo ufw allow "Nginx HTTP";
sudo su;
echo "Hello World!" > /var/www/html/index.html;
sudo service nginx restart;
