#!/usr/bin/env bash
# script installs and configures HAProxy on a ubuntu server

sudo apt-get update

sudo apt-get install -y --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.4

sudo apt-get update

sudo apt-get -y install haproxy=2.4.\*

sudo sed -i '$a \\' /etc/haproxy/haproxy.cfg

sudo sed -i '$a backend azeez_backend\n\tbalance roundrobin\n\tserver web-01 34.229.55.139:80 check\n\tserver web-02 54.90.32.207:80 check\n\nfrontend azeez_frontend\n\tbind *:80\n\tmode http\n\tacl root_url path -i -m beg /\n\tuse_backend azeez_backend if root_url\n\tdefault_backend azeez_backend' /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
