#!/usr/bin/env bash
# A Bash script that displays a list of currently running processes. It shows all processes, for all users, including those which might not have a TTY and displays them in a user-oriented format.
ps -aux
