#!/usr/bin/env bash
# Bash script that creates a file and handles signal interrupt
pgrep -f ./100-process_and_pid_file > /var/run/myscript.pid
trap "echo 'I hate the kill command'; rm /var/run/myscript.pid; exit" SIGTERM SIGQUIT
trap "echo 'Y U no love me?!'" SIGINT
while true;
do
	echo 'To infinity and beyond'
done
