#!/usr/bin/env bash
# Bash script that displays: To infinity and beyond indefinitely, With a sleep 2 in between each iteration, and I am invincible!!! when receiving a SIGTERM signal.
trap "echo  I am invincible!!!" 15
i=1
while [ $i -gt 0 ];
do
	printf "%s\n" 'To infinity and beyond'
	sleep 2
done
