#!/usr/bin/env bash
# a Bash script that displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi on a new line
times=10
i=0
while [ $i -lt $times ];
do
	echo "Best School"
	if [ $i -eq 8 ]
	then
		echo "Hi"
	fi
	i=$((i+1))
done
