#!/usr/bin/env bash
# This Bash script gives you information about the file, school in this directory
file="./school"
if [ -f $file ] || [ -d $file ]
then
	echo "school file exists"
	if  [ ! -s $file ]
	then
		echo "school file is empty"
	else
		echo "school file is not empty"
	fi
	if [ -f $file ] && [ -r $file ]
	then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
