#!/usr/bin/env bash
# Bash script that configures an Ubuntu server hosts file with two new entries
cp /etc/hosts .
echo "127.0.0.2 localhost" >> ./hosts
echo "8.8.8.8 facebook.com" >> ./hosts
cp -f ./hosts /etc/hosts
